# Generated by Django 4.0.6 on 2022-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
