# Generated by Django 4.0.6 on 2022-07-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_page_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
    ]
