version: '3.10'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  postgres_data: