version: '3.10'

services:
  web:
    build: .
    volumes:
      - ./innotter/:/home/maks/myfolder/python/Innotter/innotter
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  postgres_data: