version: '3.10'

services:

  web:
    build: .
    command: sh ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  
  db:
    image: postgres
    restart: on-failure
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 7000:7000
      - 15672:15672

  celery:
    restart: always
    container_name: celery
    build: .
    command: sh ./entrypoint_celery.sh
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
      
  localstack:
    image: localstack/localstack
    restart: on-failure
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - "4566:4566"
    volumes:
      - './setup_localstack.sh:/docker-entrypoint-initaws.d/make-s3.sh'

volumes:
  postgres_data: